import { initCoomeetMainWorldInject } from './coomeet-main-world-inject';
import { initDocumentVisibilitySpoof } from './document-visibility-spoof';
import { initFclcAlertSuppress } from './fclc-alert-suppress';
import { initFlightsimDownloadPatch } from '../sites/flightsim';
import { initArolinksGuard } from './arolinks-guard';
import { initCut4MoneyShr2Hop } from './cut4money-shr2-hop';
import { initShortxlinksFetchChain } from './shortxlinks-fetch-chain';
import { initXdmoviesLandingPageNav } from '../sites/xdmovies/landing-page-med';
import { initMultiup } from '../sites/multiup';
import { initXdmoviesMainWorldInject } from '../sites/xdmovies/mediator-page';

initCoomeetMainWorldInject();
initDocumentVisibilitySpoof();
initFclcAlertSuppress();
initFlightsimDownloadPatch();
initArolinksGuard();
initShortxlinksFetchChain();
initCut4MoneyShr2Hop();
initXdmoviesLandingPageNav();
initMultiup();
initXdmoviesMainWorldInject();
