import { initCoomeetMainWorldInject } from './coomeet-main-world-inject';
import { initDocumentVisibilitySpoof } from './document-visibility-spoof';
import { initFclcAlertSuppress, initFclcLinksGo } from '../sites/fclc';
import { initFlightsimDownloadPatch } from '../sites/flightsim';
import { initShortxlinksFetchChain } from '../sites/shortxlinks';
import { initXdmoviesLandingPageNav } from '../sites/xdmovies/landing-page-med';
import { initMultiup } from '../sites/multiup';
import { initLootlabsMainWorldInject } from '../sites/lootlabs';
import { initXdmoviesMainWorldInject } from '../sites/xdmovies/mediator-page';
import { initStudyratnaCookieDest } from '../sites/studyratna';
import { initExeioAdblockInject } from '../sites/exeio';
import { initCutyAdblockInject } from '../sites/cuty';
import { initRinkuPageHooksInject } from '../sites/rinku';
import { initStorylineScormMainWorldInject } from '../sites/storyline-scorm';

initCoomeetMainWorldInject();
initDocumentVisibilitySpoof();
initFclcAlertSuppress();
initFclcLinksGo();
initFlightsimDownloadPatch();
initShortxlinksFetchChain();
initXdmoviesLandingPageNav();
initMultiup();
initLootlabsMainWorldInject();
initXdmoviesMainWorldInject();
initStudyratnaCookieDest();
initExeioAdblockInject();
initCutyAdblockInject();
initRinkuPageHooksInject();
initStorylineScormMainWorldInject();
